name: Setup Python and Poetry
description: Installs python with poetry and setups cache
inputs:
  python-version:
    description: 'Python Version'
    default: '3.10'
    required: true
  poetry-version:
    description: 'Poetry Version'
    default: '1.1.13'
    required: false
  nexus-user:
    description: 'User for Private Repository (Nexus)'
    default: ''
    required: false
  nexus-password:
    description: 'Password for Private Repository (Nexus)'
    default: ''
    required: false

runs:
  using: "composite"
  steps:
      - name: Cache Poetry Installation
        id: cache-poetry
        uses: actions/cache@v3
        with:
          path: ~/poetry
          key: poetry-${{ inputs.POETRY_VERSION }}

      - name: Install poetry
        if: steps.cache-poetry.outputs.cache-hit != 'true'
        shell: bash
        run: curl -sSL https://install.python-poetry.org | POETRY_HOME=$HOME/poetry python3 -

      - name: Setup poetry
        shell: bash
        run: echo "$HOME/poetry/bin" >> $GITHUB_PATH

      - uses: actions/setup-python@v3
        with:
          python-version: ${{ inputs.python-version }}
          cache: 'poetry'

      - name: Set corret python version
        shell: bash
        run: poetry env use ${{ inputs.python-version }}

      - name: Set corret python version
        if: inputs.nexus-user != ''
        shell: bash
        run: poetry config http-basic.facily ${{ inputs.nexus-user }} ${{ inputs.nexus-password }}
